version: "3.8"

services:
  fastapi-backend:
    image: tgsa83609327/ai_proposal_demo:latest
    # 如果你想直接從 Dockerfile 建立映像，可以使用 build 指令，並指定上下文和 Dockerfile 路徑
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    container_name: fastapi_demo_server
    restart: always
    env_file:
      - ./backend/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
      - supabase_net

  nuxt-frontend:
    image: tgsa83609327/ai_proposal_demo_frontend:latest
    container_name: nuxt_demo_client
    restart: always
    env_file:
      - ./frontend/.env
    depends_on:
      - fastapi-backend

  nginx-proxy:
    image: nginx:latest
    # 如果你想直接從 Dockerfile 建立映像，可以使用 build 指令，並指定上下文和 Dockerfile 路徑
    # build:
    #   context: ./nginx
    #   dockerfile: Dockerfile
    container_name: nginx_demo_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # 掛載證書 (左邊是主機路徑 : 右邊是容器路徑)
      - /srv/nginx/certs:/etc/nginx/certs:ro
      # 掛載設定檔
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi-backend
      - nuxt-frontend
    networks:
      - default
      - supabase_net

networks:
  supabase_net:
    external: true
    name: supabase_default
